AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Exclude:
    - tmp/**/*
    - pkg/**/*
    - build/**/*
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Layout/LineLength:
  Enabled: false
